export const data = [
    {
      "name": "Annual Developer Conference",
      "type": "in-person",
      "description": "A three-day conference for software developers to learn about the latest technologies and best practices.",
      "category": "conference",
      "tags": ["software", "technology", "development"],
      "startDate": "2024-09-15",
      "startTime": "09:00",
      "endDate": "2024-09-17",
      "endTime": "17:00",
      "registrationDeadline": "2024-08-31",
      "venue": "Marriott Convention Center",
      "maxAttendees": 1000,
      "organizerName": "Tech Conferences Inc.",
      "organizerContact": "info@techconferences.com",
      "organizerDepartment": "Event Planning"
    },
    {
      "name": "Virtual UX Workshop",
      "type": "virtual",
      "description": "A hands-on workshop exploring the latest user experience design techniques.",
      "category": "workshop",
      "tags": ["ux", "design", "virtual"],
      "startDate": "2024-10-01",
      "startTime": "14:00",
      "endDate": "2024-10-01",
      "endTime": "17:00",
      "registrationDeadline": "2024-09-25",
      "virtualLink": "https://zoom.us/j/12345678",
      "maxAttendees": 50,
      "venue": "Marriott Convention Center",
      "organizerName": "UX Design Agency",
      "organizerContact": "workshops@uxdesign.com",
      "organizerDepartment": "Training"
    },
    {
      "name": "Hybrid Data Science Meetup",
      "type": "hybrid",
      "description": "A monthly meetup where data scientists share their latest projects and techniques.",
      "category": "meetup",
      "tags": ["data science", "machine learning", "analysis"],
      "startDate": "2024-11-18",
      "startTime": "18:30",
      "endDate": "2024-11-18",
      "endTime": "20:30",
      "registrationDeadline": "2024-11-15",
      "venue": "Tech Hub Conference Room",
      "virtualLink": "https://meet.google.com/abc-defg-hij",
      "maxAttendees": 75,
      "organizerName": "Data Science Enthusiasts Club",
      "organizerContact": "meetup@datascience.org",
      "organizerDepartment": "Community Engagement"
    },
    {
      "name": "Introduction to Blockchain Webinar",
      "type": "virtual",
      "description": "A webinar covering the fundamentals of blockchain technology and its real-world applications.",
      "category": "webinar",
      "tags": ["blockchain", "cryptocurrency", "technology"],
      "startDate": "2024-12-05",
      "startTime": "11:00",
      "endDate": "2024-12-05",
      "endTime": "12:30",
      "registrationDeadline": "2024-12-03",
      "virtualLink": "https://attendee.gotowebinar.com/register/1234567890",
      "maxAttendees": 500,
      "organizerName": "Blockchain Experts Institute",
      "organizerContact": "webinars@blockchainexperts.edu",
      "organizerDepartment": "Education"
    },
    {
      "name": "Sustainable Fashion Pop-up Shop",
      "type": "in-person",
      "description": "A one-day pop-up shop featuring ethically-sourced and environmentally-friendly fashion items.",
      "category": "other",
      "tags": ["fashion", "sustainability", "pop-up"],
      "startDate": "2025-01-20",
      "startTime": "10:00",
      "endDate": "2025-01-20",
      "endTime": "18:00",
      "registrationDeadline": "2025-01-15",
      "venue": "Community Arts Center",
      "maxAttendees": 200,
      "organizerName": "Eco-Chic Collective",
      "organizerContact": "popupshop@ecochic.org",
      "organizerDepartment": "Retail"
    },
    {
      "name": "Machine Learning Meetup",
      "type": "virtual",
      "description": "A virtual meetup for machine learning enthusiasts to share projects and discuss new techniques.",
      "category": "meetup",
      "tags": ["machine learning", "ai", "data science"],
      "startDate": "2024-09-22",
      "startTime": "19:00",
      "endDate": "2024-09-22",
      "endTime": "20:30",
      "registrationDeadline": "2024-09-20",
      "virtualLink": "https://teams.microsoft.com/l/meetup-join/19%3ameeting_NTY3NDQ2NGEtNDQwMC00MDdmLTg3YjEtYTAzNmZjNmNjMGVi%40thread.v2/0?context=%7b%22Tid%22%3a%22c4e675d0-3d10-4366-b876-b4a749a5167b%22%2c%22Oid%22%3a%22b8745678-1234-5678-9012-345678901234%22%7d",
      "maxAttendees": 100,
      "organizerName": "AI Enthusiasts Club",
      "organizerContact": "meetup@aiclub.org",
      "organizerDepartment": "Community"
    },
    {
      "name": "Agile Project Management Workshop",
      "type": "in-person",
      "description": "A hands-on workshop on implementing Agile project management techniques.",
      "category": "workshop",
      "tags": ["agile", "project management", "scrum"],
      "startDate": "2024-10-04",
      "startTime": "09:00",
      "endDate": "2024-10-04",
      "endTime": "17:00",
      "registrationDeadline": "2024-09-30",
      "venue": "Hilton Conference Center",
      "maxAttendees": 50,
      "organizerName": "Agile Consulting Group",
      "organizerContact": "workshops@agileconsulting.com",
      "organizerDepartment": "Training"
    },
    {
      "name": "Blockchain for Supply Chain Conference",
      "type": "hybrid",
      "description": "A conference exploring the applications of blockchain technology in supply chain management.",
      "category": "conference",
      "tags": ["blockchain", "supply chain", "logistics"],
      "startDate": "2024-11-07",
      "startTime": "08:30",
      "endDate": "2024-11-08",
      "endTime": "17:00",
      "registrationDeadline": "2024-10-31",
      "venue": "Convention Center Auditorium",
      "virtualLink": "https://conference.blockchain-supply.com/livestream",
      "maxAttendees": 300,
      "organizerName": "Blockchain Supply Chain Association",
      "organizerContact": "conference@blockchainsupply.org",
      "organizerDepartment": "Events"
    },
    {
      "name": "Emotional Intelligence Webinar",
      "type": "virtual",
      "description": "A webinar on developing emotional intelligence skills for personal and professional growth.",
      "category": "webinar",
      "tags": ["emotional intelligence", "personal development", "leadership"],
      "startDate": "2024-12-15",
      "startTime": "13:00",
      "endDate": "2024-12-15",
      "endTime": "14:30",
      "registrationDeadline": "2024-12-10",
      "virtualLink": "https://register.gotowebinar.com/register/9876543210",
      "maxAttendees": 1000,
      "organizerName": "Personal Growth Institute",
      "organizerContact": "webinars@personalgrowth.edu",
      "organizerDepartment": "Education"
    },
    {
      "name": "Sustainable Gardening Workshop",
      "type": "in-person",
      "description": "A hands-on workshop on creating and maintaining a sustainable home garden.",
      "category": "workshop",
      "tags": ["gardening", "sustainability", "environment"],
      "startDate": "2025-01-28",
      "startTime": "10:00",
      "endDate": "2025-01-28",
      "endTime": "15:00",
      "registrationDeadline": "2025-01-24",
      "venue": "Community Gardens",
      "maxAttendees": 30,
      "organizerName": "Eco-Friendly Gardening Club",
      "organizerContact": "workshops@ecogarden.org",
      "organizerDepartment": "Education"
    },
    {
      "name": "Graphic Design Meetup",
      "type": "virtual",
      "description": "A virtual meetup for graphic designers to share their work and discuss design trends.",
      "category": "meetup",
      "tags": ["graphic design", "art", "creativity"],
      "startDate": "2025-02-10",
      "startTime": "20:00",
      "endDate": "2025-02-10",
      "endTime": "21:30",
      "registrationDeadline": "2025-02-08",
      "virtualLink": "https://zoom.us/j/98765432101",
      "maxAttendees": 75,
      "organizerName": "Design Enthusiasts Group",
      "organizerContact": "meetup@designenthusiasts.com",
      "organizerDepartment": "Community"
    },
    {
      "name": "Cybersecurity Conference",
      "type": "in-person",
      "description": "A two-day conference on the latest trends and best practices in cybersecurity.",
      "category": "conference",
      "tags": ["cybersecurity", "information security", "technology"],
      "startDate": "2025-03-18",
      "startTime": "09:00",
      "endDate": "2025-03-19",
      "endTime": "17:00",
      "registrationDeadline": "2025-03-10",
      "venue": "Marriott Convention Center",
      "maxAttendees": 500,
      "organizerName": "Cybersecurity Professionals Association",
      "organizerContact": "conference@cyberpro.org",
      "organizerDepartment": "Events"
    },
    {
      "name": "Intro to React.js Webinar",
      "type": "virtual",
      "description": "A webinar covering the fundamentals of the React.js JavaScript library for building user interfaces.",
      "category": "webinar",
      "tags": ["react.js", "javascript", "web development"],
      "startDate": "2025-04-04",
      "startTime": "12:00",
      "endDate": "2025-04-04",
      "endTime": "13:30",
      "registrationDeadline": "2025-04-01",
      "virtualLink": "https://attendee.gotowebinar.com/register/0987654321",
      "maxAttendees": 300,
      "organizerName": "Web Development Academy",
      "organizerContact": "webinars@webdevacademy.edu",
      "organizerDepartment": "Education"
    },
    {
      "name": "Mindfulness and Wellness Retreat",
      "type": "in-person",
      "description": "A weekend-long retreat focused on mindfulness practices and overall wellness.",
      "category": "other",
      "tags": ["mindfulness", "wellness", "retreat"],
      "startDate": "2025-05-17",
      "startTime": "16:00",
      "endDate": "2025-05-19",
      "endTime": "14:00",
      "registrationDeadline": "2025-05-10",
      "venue": "Mountain View Retreat Center",
      "maxAttendees": 40,
      "organizerName": "Mindfulness Institute",
      "organizerContact": "retreats@mindfulnessinstitute.org",
      "organizerDepartment": "Programming"
    },
    {
      "name": "Data Visualization Workshop",
      "type": "hybrid",
      "description": "A workshop on creating effective data visualizations using the latest tools and techniques.",
      "category": "workshop",
      "tags": ["data visualization", "business intelligence", "analytics"],
      "startDate": "2025-06-02",
      "startTime": "09:00",
      "endDate": "2025-06-02",
      "endTime": "17:00",
      "registrationDeadline": "2025-05-27",
      "venue": "Innovation Center",
      "virtualLink": "https://meet.google.com/xyz-abc-123",
      "maxAttendees": 75,
      "organizerName": "Data Visualization Experts",
      "organizerContact": "workshops@datavis.com",
      "organizerDepartment": "Training"
    },
    {
      "name": "Sustainable Fashion Design Workshop",
      "type": "in-person",
      "description": "A hands-on workshop teaching sustainable fashion design techniques and principles.",
      "category": "workshop",
      "tags": ["fashion", "sustainability", "design"],
      "startDate": "2025-07-15",
      "startTime": "10:00",
      "endDate": "2025-07-15",
      "endTime": "16:00",
      "registrationDeadline": "2025-07-10",
      "venue": "Community Arts Center",
      "maxAttendees": 25,
      "organizerName": "Eco-Fashion Collective",
      "organizerContact": "workshops@ecofashion.org",
      "organizerDepartment": "Education"
    },
    {
      "name": "Blockchain for Enterprise Webinar Series",
      "type": "virtual",
      "description": "A 3-part webinar series exploring the application of blockchain technology in enterprise business processes.",
      "category": "webinar",
      "tags": ["blockchain", "enterprise", "business"],
      "startDate": "2025-08-01",
      "startTime": "14:00",
      "endDate": "2025-08-15",
      "endTime": "15:00",
      "registrationDeadline": "2025-07-28",
      "virtualLink": "https://register.gotowebinar.com/register/1234567890",
      "maxAttendees": 500,
      "organizerName": "Blockchain Enterprise Solutions",
      "organizerContact": "webinars@blockchainenterprise.com",
      "organizerDepartment": "Marketing"
    },
    {
      "name": "DevOps Meetup",
      "type": "hybrid",
      "description": "A monthly meetup for DevOps professionals to share best practices and discuss industry trends.",
      "category": "meetup",
      "tags": ["devops", "software development", "automation"],
      "startDate": "2025-09-20",
      "startTime": "18:30",
      "endDate": "2025-09-20",
      "endTime": "20:30",
      "registrationDeadline": "2025-09-15",
      "venue": "Tech Hub Auditorium",
      "virtualLink": "https://meet.google.com/abc-def-ghi",
      "maxAttendees": 100,
      "organizerName": "DevOps Enthusiasts Club",
      "organizerContact": "meetup@devopsclub.org",
      "organizerDepartment": "Community"
    },
    {
      "name": "AI for Social Good Conference",
      "type": "in-person",
      "description": "A conference exploring the application of artificial intelligence to address global social and environmental challenges.",
      "category": "conference",
      "tags": ["ai", "social impact", "sustainability"],
      "startDate": "2025-10-10",
      "startTime": "09:00",
      "endDate": "2025-10-11",
      "endTime": "17:00",
      "registrationDeadline": "2025-10-01",
      "venue": "Convention Center",
      "maxAttendees": 400,
      "organizerName": "AI for Social Good Foundation",
      "organizerContact": "conference@aisocialgood.org",
      "organizerDepartment": "Events"
    },
    {
      "name": "Introduction to Quantum Computing Webinar",
      "type": "virtual",
      "description": "A webinar providing an overview of quantum computing and its potential impact on various industries.",
      "category": "webinar",
      "tags": ["quantum computing", "technology", "innovation"],
      "startDate": "2025-11-01",
      "startTime": "11:00",
      "endDate": "2025-11-01",
      "endTime": "12:30",
      "registrationDeadline": "2025-10-27",
      "virtualLink": "https://attendee.gotowebinar.com/register/9876543210",
      "maxAttendees": 300,
      "organizerName": "Quantum Computing Institute",
      "organizerContact": "webinars@quantumcomputing.edu",
      "organizerDepartment": "Education"
    }
  ]